language: objective-c
xcode_workspace: Tests/CocoaLUTTests.xcworkspace
xcode_scheme: CocoaLUTTests
before_script:
  - sudo easy_install cpp-coveralls
before_install:
  - gem install cocoapods --no-rdoc --no-ri
  - pod repo remove master
  - pod setup
install:
  - cd Tests
  - pod install
  - cd ..
after_success:
  - ./Tests/coveralls.rb --extension m --exclude-folder Tests --exclude-folder CocoaLUTTests
